"use strict";

const { v4: uuidv4 } = require("uuid");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Menu", [
      {
        id: uuidv4(),
        nama: "PaNas 2 Ayam McD Gulai Spicy Perkedel",
        harga_awal: 65500,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 2 Ayam McD Gulai Perkedel.webp",
        ketersediaan: "Tersedia",
        tag: "Baru!",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 2 with Fries Ayam McD Gulai Spicy",
        harga_awal: 80500,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 2 Fries Ayam McD Gulai.webp",
        ketersediaan: "Tersedia",
        tag: "Baru!",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "Paket Spesial Ayam McD Gulai Spicy Perkedel",
        harga_awal: 57500,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/Paket Spesial Ayam McD Gulai Perkedel.webp",
        ketersediaan: "Tersedia",
        tag: "Baru!",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 1 Spicy, Medium",
        harga_awal: 36500,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 1 Spicy.png",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 2 Spicy, Medium",
        harga_awal: 48500,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 2 Spicy.png",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 2 with Fries Spicy",
        harga_awal: 51000,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 2 with Fries Spicy.png",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaMer 5 Spicy",
        harga_awal: 88000,
        kategori: "Ayam McD Spicy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaMer 5 Spicy.png",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "Ayam Spicy McDonald's",
        harga_awal: 22000,
        kategori: "Ayam McD Spicy",
        tipe: "Ala Carte",
        gambar: "http://localhost:3000/uploads/assets/Ayam Spicy McDonald's.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 1 Krispy, Medium",
        harga_awal: 36500,
        kategori: "Ayam McD Krispy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 1 Krispy.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas Special Krispy",
        harga_awal: 45000,
        kategori: "Ayam McD Krispy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas Special Krispy.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 2 Krispy, Medium",
        harga_awal: 48500,
        kategori: "Ayam McD Krispy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 2 Krispy.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaNas 2 Krispy with Fries, Medium",
        harga_awal: 51000,
        kategori: "Ayam McD Krispy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaNas 2 Krispy with Fries.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaMer 5 Krispy",
        harga_awal: 88000,
        kategori: "Ayam McD Krispy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaMer 5 Krispy.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "PaMer 7 Krispy",
        harga_awal: 12000,
        kategori: "Ayam McD Krispy",
        tipe: "Paket",
        gambar: "http://localhost:3000/uploads/assets/PaMer 7 Krispy.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: uuidv4(),
        nama: "Tehbotol Kotak",
        harga_awal: 11000,
        kategori: "Minuman",
        tipe: "Ala Carte",
        gambar: "http://localhost:3000/uploads/assets/Tehbotol Sosro Kotak.webp",
        ketersediaan: "Tersedia",
        tag: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Menu", null, {});
  },
};